#!/bin/bash
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/toc @jupyter-widgets/jupyterlab-manager jupyterlab-plotly plotlywidget nbdime-jupyterlab